libs =
import libs += libboost-program-options%lib{boost_program_options}
import libs += libboost-filesystem%lib{boost_filesystem}
import libs += libcrails-renderer%lib{crails-renderer}
import libs += libcrails-templates%lib{crails-templates}
import libs += libcrails-semantics%lib{crails-semantics}
import libs += libcrails-readfile%lib{crails-readfile}
import libs += libdatatree%lib{datatree}
import libs += libbacktrace%lib{backtrace}

exe{ecpp}: {hxx ixx txx cxx}{**} $libs testscript

cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.loptions =+ "-Wl,--start-group"
